// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pleaseworkplease;

#nullable disable

namespace pleaseworkplease.Migrations
{
    [DbContext(typeof(StarterBaseContext))]
    partial class StarterBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pleaseworkplease.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Genre");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("keyword");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("pleaseworkplease.Novel", b =>
                {
                    b.Property<int>("Isbn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Isbn"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Isbn");

                    b.HasIndex("Genre");

                    b.ToTable("Novels");
                });

            modelBuilder.Entity("pleaseworkplease.Novel", b =>
                {
                    b.HasOne("pleaseworkplease.Genre", "GenreNavigation")
                        .WithMany("Novels")
                        .HasForeignKey("Genre")
                        .IsRequired()
                        .HasConstraintName("FK_Novels_Genre");

                    b.Navigation("GenreNavigation");
                });

            modelBuilder.Entity("pleaseworkplease.Genre", b =>
                {
                    b.Navigation("Novels");
                });
#pragma warning restore 612, 618
        }
    }
}
